# Generated by Django 4.2 on 2023-04-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='end_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время оканчания'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='start_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время работы'),
        ),
    ]
